# Generated by Django 4.2.7 on 2023-11-29 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateField(default=django.utils.timezone.now)),
                ('orderAddress', models.TextField(max_length=50)),
                ('orderCost', models.IntegerField()),
                ('orderPhoneNumber', models.IntegerField()),
                ('orderPayment', models.TextField(choices=[('ОН', 'Онлайн оплата'), ('КП', 'Картой при получении'), ('НП', 'Наличными при получении')])),
                ('orderStatus', models.TextField(choices=[('ОП', 'Оплачен'), ('СЗ', 'Сбор заказа'), ('ДС', 'Доставка курьером'), ('ДО', 'Доставлен')])),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductAmount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.TextField(max_length=50)),
                ('productType', models.TextField(choices=[('Овощи', 'Овощи'), ('Фрукты', 'Фрукты'), ('Готовая продукция', 'Готовая продукция'), ('Прочее', 'Прочее')])),
                ('productCost', models.IntegerField()),
                ('productDescription', models.TextField()),
                ('productImg', models.TextField(default='static/img/logo1.png')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.EmailField(max_length=30)),
                ('requestText', models.TextField()),
            ],
        ),
    ]
