# Generated by Django 4.2.5 on 2023-11-26 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderEmployee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.employee'),
        ),
        migrations.AddField(
            model_name='order',
            name='orderUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
        migrations.AlterField(
            model_name='request',
            name='userId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('OPId', models.IntegerField(primary_key=True, serialize=False)),
                ('ProductAmount', models.IntegerField()),
                ('OrderId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.order')),
                ('ProductId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
